/**
 * tests/auditKeyStoreTest.ts
 *
 * Gate for the opt-in macOS Keychain store for the Ed25519 audit signing key.
 *
 * The key on disk is 0600 but owned by the same account the monitored agent runs
 * as, so the agent can read it and — the part that actually matters — delete it,
 * let the service mint a replacement, and have a fabricated history verify
 * cleanly under the new identity. Moving the key into the Keychain takes it out
 * of `cat`/`rm` range without a second OS account or a single `sudo`.
 *
 * What this file has to prove, in order of how badly each would hurt:
 *
 *   1. NOTHING MIGRATES ON ITS OWN. With no pointer file the resolver behaves
 *      exactly as it did before the Keychain existed, on every platform.
 *   2. THE KEY ROUND-TRIPS. After migration a signature produced through the
 *      Keychain verifies against the ORIGINAL on-disk public key, and the keyId
 *      is unchanged — the identity every past record is bound to survived.
 *   3. MIGRATION NEVER DELETES. The private key file is left alone by default,
 *      and `--remove-file` renames it aside rather than removing it.
 *   4. A MISSING KEYCHAIN ITEM DEGRADES TO UNSIGNED, NEVER TO A NEW KEY. This is
 *      the dangerous failure: silently minting a replacement would make forged
 *      history verify perfectly under a key no verifier has ever seen.
 *   5. IT IS REVERSIBLE. `to-file` restores the file store with the same keyId.
 *   6. NO KEYCHAIN, NO CHANGE. On Linux/Docker/CI the file path is untouched and
 *      the migration refuses cleanly instead of half-applying.
 *
 * Run via:  npx tsx tests/auditKeyStoreTest.ts
 *
 * KEY DISCIPLINE: every key here is generated by this test into a temp
 * CLAUDESEC_HOME, and every Keychain write goes to a throwaway keychain created
 * in a temp dir and deleted in the finally block. The operator's real signing
 * key and real login keychain are never read, written, or named.
 */

import assert from 'node:assert';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

let passed = 0;
let failed = 0;
const failures: string[] = [];

async function check(name: string, fn: () => void | Promise<void>): Promise<void> {
  try { await fn(); passed++; }
  catch (err) { failed++; failures.push(`${name}: ${(err as Error).message}`); }
}

const HOME_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'csec-keystore-home-'));
const KC_DIR   = fs.mkdtempSync(path.join(os.tmpdir(), 'csec-keystore-kc-'));
const KC_PATH  = path.join(KC_DIR, 'claudesec-test.keychain-db');
const KC_PASS  = crypto.randomBytes(16).toString('hex');

const HOOKS_DIR = path.join(HOME_DIR, 'hooks');
const KEY_FILE  = path.join(HOOKS_DIR, 'audit-key.ed25519.pem');
const STORE_PTR = path.join(HOOKS_DIR, 'audit-key.store.json');

// Set BEFORE importing auditChain so no path resolves against the real home.
process.env.CLAUDESEC_HOME             = HOME_DIR;
process.env.CLAUDESEC_KEYCHAIN_PATH    = KC_PATH;
process.env.CLAUDESEC_KEYCHAIN_SERVICE = `ClaudeSec TEST audit key ${process.pid}`;
process.env.CLAUDESEC_KEYCHAIN_ACCOUNT = `test-audit-key-${process.pid}`;

const IS_DARWIN = process.platform === 'darwin' && fs.existsSync('/usr/bin/security');

function makeKeychain(): void {
  execFileSync('/usr/bin/security', ['create-keychain', '-p', KC_PASS, KC_PATH], { stdio: 'ignore' });
  execFileSync('/usr/bin/security', ['unlock-keychain', '-p', KC_PASS, KC_PATH], { stdio: 'ignore' });
}

function destroyKeychain(): void {
  try { execFileSync('/usr/bin/security', ['delete-keychain', KC_PATH], { stdio: 'ignore' }); } catch {}
}

function cleanup(): void {
  destroyKeychain();
  try { fs.rmSync(HOME_DIR, { recursive: true, force: true }); } catch {}
  try { fs.rmSync(KC_DIR,   { recursive: true, force: true }); } catch {}
}

async function main(): Promise<void> {
  const chain = await import('../server/auditChain.js');
  const {
    auditKeyStoreStatus, migrateAuditKeyToKeychain, revertAuditKeyToFile,
    resetSigningKeyCacheForTests, signWithAuditKey, isAuditSigned, auditKeyId,
  } = chain;

  // A throwaway key pair, founded by this test — never the operator's.
  fs.mkdirSync(HOOKS_DIR, { recursive: true, mode: 0o700 });
  const { privateKey, publicKey } = crypto.generateKeyPairSync('ed25519');
  const PRIVATE_PEM = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString();
  const PUBLIC_PEM  = publicKey.export({ type: 'spki', format: 'pem' }).toString();
  fs.writeFileSync(KEY_FILE, PRIVATE_PEM, { mode: 0o600 });

  /** Does `sig` verify against the ORIGINAL public key this test generated? */
  const verifiesAgainstOriginal = (data: Buffer, sig: Buffer | null): boolean =>
    sig !== null && crypto.verify(null, data, PUBLIC_PEM, sig);

  let originalKeyId = '';

  try {
    // ── 1. Baseline: the file store, unchanged ─────────────────────────────
    await check('with no pointer file the key is served from disk', () => {
      resetSigningKeyCacheForTests();
      const s = auditKeyStoreStatus();
      assert.strictEqual(s.store, 'file');
      assert.strictEqual(s.fileExists, true);
      assert.strictEqual(s.degraded, false);
      assert.ok(s.keyId, 'the file store should report a keyId');
      originalKeyId = s.keyId;
    });

    await check('the file-backed key signs, and the signature verifies', () => {
      resetSigningKeyCacheForTests();
      const nonce = crypto.randomBytes(32);
      assert.ok(verifiesAgainstOriginal(nonce, signWithAuditKey(nonce)),
        'the on-disk key must produce a verifiable signature before we move anything');
      assert.strictEqual(auditKeyId(), originalKeyId);
    });

    if (!IS_DARWIN) {
      // ── 6. No Keychain: nothing changes, and migration refuses cleanly ────
      await check('without a Keychain the migration refuses and changes nothing', () => {
        const r = migrateAuditKeyToKeychain();
        assert.strictEqual(r.ok, false, 'migration must not claim success without a Keychain');
        assert.strictEqual(fs.existsSync(STORE_PTR), false, 'no pointer file may be written');
        assert.strictEqual(fs.readFileSync(KEY_FILE, 'utf8'), PRIVATE_PEM, 'the key file must be untouched');
        resetSigningKeyCacheForTests();
        assert.strictEqual(auditKeyStoreStatus().store, 'file');
        assert.strictEqual(isAuditSigned(), true, 'signing must keep working on the file path');
      });
      return;
    }

    makeKeychain();

    // ── 2 + 3. Migration ───────────────────────────────────────────────────
    await check('migrating moves the key into the Keychain and keeps the identity', () => {
      const r = migrateAuditKeyToKeychain();
      assert.strictEqual(r.ok, true, `migration failed: ${r.message}`);
      assert.strictEqual(r.keyId, originalKeyId,
        'the keyId MUST survive migration — a new identity would orphan every past record');
      assert.strictEqual(fs.existsSync(STORE_PTR), true, 'the pointer file should now exist');
      const ptr = JSON.parse(fs.readFileSync(STORE_PTR, 'utf8')) as { store: string; keyId: string };
      assert.strictEqual(ptr.store, 'keychain');
      assert.strictEqual(ptr.keyId, originalKeyId);
      assert.strictEqual(fs.statSync(STORE_PTR).mode & 0o777, 0o600);
    });

    await check('migration leaves the key file exactly where it was', () => {
      assert.strictEqual(fs.existsSync(KEY_FILE), true,
        'the default migration must not remove the file — reversibility depends on it');
      assert.strictEqual(fs.readFileSync(KEY_FILE, 'utf8'), PRIVATE_PEM);
    });

    await check('the Keychain-held key round-trips a signature', () => {
      resetSigningKeyCacheForTests();
      const s = auditKeyStoreStatus();
      assert.strictEqual(s.store, 'keychain', 'the Keychain must now be authoritative');
      assert.strictEqual(s.degraded, false);
      assert.strictEqual(s.keychainHasItem, true);
      assert.strictEqual(s.keyId, originalKeyId);

      resetSigningKeyCacheForTests();
      const nonce = crypto.randomBytes(32);
      const sig = signWithAuditKey(nonce);
      assert.ok(verifiesAgainstOriginal(nonce, sig),
        'a signature made with the Keychain-held key must verify against the ORIGINAL public key');
      assert.strictEqual(auditKeyId(), originalKeyId);
    });

    await check('the same key signs different messages to different signatures', () => {
      resetSigningKeyCacheForTests();
      const a = crypto.randomBytes(32);
      const b = crypto.randomBytes(32);
      const sigA = signWithAuditKey(a);
      const sigB = signWithAuditKey(b);
      assert.ok(sigA && sigB);
      assert.notStrictEqual(sigA!.toString('hex'), sigB!.toString('hex'));
      assert.ok(verifiesAgainstOriginal(a, sigA) && verifiesAgainstOriginal(b, sigB));
      assert.strictEqual(crypto.verify(null, a, PUBLIC_PEM, sigB!), false,
        'a signature must not verify over the wrong message');
    });

    // ── 4. The dangerous failure mode ──────────────────────────────────────
    await check('an unreadable Keychain item degrades to UNSIGNED, never to a new key', () => {
      // Simulate a locked keychain / revoked item by removing it outright, which
      // is the strongest form of the same failure.
      execFileSync('/usr/bin/security', [
        'delete-generic-password',
        '-a', process.env.CLAUDESEC_KEYCHAIN_ACCOUNT!,
        '-s', process.env.CLAUDESEC_KEYCHAIN_SERVICE!,
        KC_PATH,
      ], { stdio: 'ignore' });

      resetSigningKeyCacheForTests();
      assert.strictEqual(isAuditSigned(), false, 'an unreachable key must report unsigned');
      assert.strictEqual(signWithAuditKey(crypto.randomBytes(32)), null,
        'signing must fail closed rather than silently use a different key');
      assert.strictEqual(auditKeyId(), '', 'no keyId may be reported while the key is unreachable');

      const s = auditKeyStoreStatus();
      assert.strictEqual(s.store, 'keychain');
      assert.strictEqual(s.degraded, true, 'status must surface the degradation, not hide it');

      // The critical assertion: the file on disk was NOT overwritten with a
      // freshly minted key, and no new identity was founded anywhere.
      assert.strictEqual(fs.readFileSync(KEY_FILE, 'utf8'), PRIVATE_PEM,
        'a missing Keychain item must never cause a replacement key to be minted');
    });

    // ── 5. Reversible ──────────────────────────────────────────────────────
    await check('reverting recovers from disk when the Keychain item is gone', () => {
      const r = revertAuditKeyToFile();
      assert.strictEqual(r.ok, true, `revert failed: ${r.message}`);
      assert.strictEqual(r.keyId, originalKeyId);
      assert.strictEqual(fs.existsSync(STORE_PTR), false, 'the pointer file must be removed');
      assert.strictEqual(fs.readFileSync(KEY_FILE, 'utf8'), PRIVATE_PEM);

      resetSigningKeyCacheForTests();
      assert.strictEqual(auditKeyStoreStatus().store, 'file');
      const nonce = crypto.randomBytes(32);
      assert.ok(verifiesAgainstOriginal(nonce, signWithAuditKey(nonce)),
        'signing must work again from the file store');
    });

    // ── 3b. --remove-file renames, never deletes ───────────────────────────
    await check('--remove-file parks the key file aside instead of deleting it', () => {
      resetSigningKeyCacheForTests();
      const r = migrateAuditKeyToKeychain({ removeFile: true });
      assert.strictEqual(r.ok, true, `migration failed: ${r.message}`);
      assert.strictEqual(fs.existsSync(KEY_FILE), false, 'the key file should have been moved');
      const parked = `${KEY_FILE}.migrated`;
      assert.strictEqual(fs.existsSync(parked), true, 'the key must be renamed, never deleted');
      assert.strictEqual(fs.readFileSync(parked, 'utf8'), PRIVATE_PEM);
      assert.strictEqual(fs.statSync(parked).mode & 0o777, 0o600);

      resetSigningKeyCacheForTests();
      const nonce = crypto.randomBytes(32);
      assert.ok(verifiesAgainstOriginal(nonce, signWithAuditKey(nonce)),
        'the Keychain copy must still sign after the file was parked');
    });

    await check('reverting restores the key file from the Keychain', () => {
      const r = revertAuditKeyToFile();
      assert.strictEqual(r.ok, true, `revert failed: ${r.message}`);
      assert.strictEqual(fs.existsSync(KEY_FILE), true, 'the key file must come back');
      assert.strictEqual(fs.readFileSync(KEY_FILE, 'utf8'), PRIVATE_PEM,
        'the restored file must be byte-identical to the original key');
      assert.strictEqual(fs.statSync(KEY_FILE).mode & 0o777, 0o600);
      assert.strictEqual(fs.existsSync(`${KEY_FILE}.migrated`), false, 'the parked copy should be cleaned up');
      assert.strictEqual(fs.existsSync(STORE_PTR), false);

      resetSigningKeyCacheForTests();
      assert.strictEqual(auditKeyStoreStatus().store, 'file');
      assert.strictEqual(auditKeyId(), originalKeyId);
    });

    await check('a second migration is refused while one is already in effect', () => {
      assert.strictEqual(migrateAuditKeyToKeychain().ok, true);
      const again = migrateAuditKeyToKeychain();
      assert.strictEqual(again.ok, false, 'migrating twice must be a no-op, not a re-write');
      assert.match(again.message, /already/i);
      assert.strictEqual(revertAuditKeyToFile().ok, true);
    });

    await check('reverting when nothing was migrated is a refused no-op', () => {
      const r = revertAuditKeyToFile();
      assert.strictEqual(r.ok, false);
      assert.match(r.message, /already/i);
      assert.strictEqual(fs.readFileSync(KEY_FILE, 'utf8'), PRIVATE_PEM);
    });

    // ── 6b. Keychain present but unusable ──────────────────────────────────
    await check('a Keychain that cannot be written fails the migration cleanly', () => {
      const saved = process.env.CLAUDESEC_KEYCHAIN_PATH;
      process.env.CLAUDESEC_KEYCHAIN_PATH = path.join(KC_DIR, 'does-not-exist.keychain-db');
      try {
        const r = migrateAuditKeyToKeychain();
        assert.strictEqual(r.ok, false, 'migration into a nonexistent keychain must fail');
        assert.strictEqual(fs.existsSync(STORE_PTR), false, 'a failed migration must leave no pointer');
        assert.strictEqual(fs.readFileSync(KEY_FILE, 'utf8'), PRIVATE_PEM);
        resetSigningKeyCacheForTests();
        assert.strictEqual(isAuditSigned(), true, 'the file store must still work after a failed migration');
      } finally {
        process.env.CLAUDESEC_KEYCHAIN_PATH = saved;
      }
    });
  } finally {
    cleanup();
  }

  const total = passed + failed;
  console.log('───────────────────────────────────────────────');
  console.log(`  auditKeyStoreTest: ${passed}/${total} passed${IS_DARWIN ? '' : ' (non-darwin: Keychain cases skipped)'}`);
  console.log('───────────────────────────────────────────────');
  if (failed > 0) {
    console.error(`\n  ${failed} FAILURE(S):`);
    for (const f of failures) console.error(`    ✗ ${f}`);
    process.exit(1);
  }
  process.exit(0);
}

main().catch(err => {
  console.error('[auditKeyStoreTest] fatal:', err);
  cleanup();
  process.exit(1);
});
